In [1]:
import numpy as np

# New Section

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#iot=pd.read_csv(r"http://localhost:8888/edit/Documents/working_projects/AI_ML/cleaned_iot.csv")

# Provide the correct absolute file path to your CSV file
file_path = r"C:\Users\hp\Documents\working_projects\AI_ML\cleaned_iot.csv"

# Read the CSV file
iot = pd.read_csv(file_path)


In [4]:
iot.head()

flow_duration  Header_Length  Protocol Type  Duration         Rate  \
0       0.000000          54.00           6.00     64.00     0.329807   
1       0.000000          57.04           6.33     64.00     4.290556   
2       0.000000           0.00           1.00     64.00    33.396799   
3       0.328175       76175.00          17.00     64.00  4642.133010   
4       0.117320         101.73           6.11     65.91     6.202211   

         Srate  Drate  fin_flag_number  syn_flag_number  rst_flag_number  ...  \
0     0.329807    0.0                1                0                1  ...   
1     4.290556    0.0                0                0                0  ...   
2    33.396799    0.0                0                0                0  ...   
3  4642.133010    0.0                0                0                0  ...   
4     6.202211    0.0                0                1                0  ...   

         Std  Tot size          IAT  Number   Magnitue     Radius  \
0   0.000000     54.00  83343831.92     9.5  10.392305   0.000000   
1   2.822973     57.04  82926067.47     9.5  10.464666   4.010353   
2   0.000000     42.00  83127993.93     9.5   9.165151   0.000000   
3   0.000000     50.00  83015696.38     9.5  10.000000   0.000000   
4  23.113111     57.88  82972999.18     9.5  11.346876  32.716243   

    Covariance  Variance  Weight             label  
0     0.000000      0.00  141.55  DDoS-RSTFINFlood  
1   160.987842      0.05  141.55     DoS-TCP_Flood  
2     0.000000      0.00  141.55   DDoS-ICMP_Flood  
3     0.000000      0.00  141.55     DoS-UDP_Flood  
4  3016.808286      0.19  141.55     DoS-SYN_Flood  

[5 rows x 47 columns]

In [5]:
iot.describe()

flow_duration  Header_Length  Protocol Type      Duration  \
count   1.048575e+06   1.048575e+06   1.048575e+06  1.048575e+06   
mean    5.763553e+00   7.759537e+04   9.062979e+00  6.635523e+01   
std     2.965660e+02   4.664043e+05   8.936737e+00  1.408680e+01   
min     0.000000e+00   0.000000e+00   0.000000e+00  0.000000e+00   
25%     0.000000e+00   5.400000e+01   6.000000e+00  6.400000e+01   
50%     0.000000e+00   5.400000e+01   6.000000e+00  6.400000e+01   
75%     1.042881e-01   2.781200e+02   1.428000e+01  6.400000e+01   
max     9.943576e+04   9.815555e+06   4.700000e+01  2.550000e+02   

               Rate         Srate         Drate  fin_flag_number  \
count  1.048575e+06  1.048575e+06  1.048575e+06     1.048575e+06   
mean   9.146945e+03  9.146945e+03  1.807621e-06     8.655842e-02   
std    9.974794e+04  9.974794e+04  8.501385e-04     2.811870e-01   
min    0.000000e+00  0.000000e+00  0.000000e+00     0.000000e+00   
25%    2.087155e+00  2.087155e+00  0.000000e+00     0.000000e+00   
50%    1.581371e+01  1.581371e+01  0.000000e+00     0.000000e+00   
75%    1.174380e+02  1.174380e+02  0.000000e+00     0.000000e+00   
max    7.340032e+06  7.340032e+06  8.484654e-01     1.000000e+00   

       syn_flag_number  rst_flag_number  ...           AVG           Std  \
count     1.048575e+06     1.048575e+06  ...  1.048575e+06  1.048575e+06   
mean      2.073090e-01     9.057149e-02  ...  1.248502e+02  3.345817e+01   
std       4.053790e-01     2.869989e-01  ...  2.420296e+02  1.622552e+02   
min       0.000000e+00     0.000000e+00  ...  4.200000e+01  0.000000e+00   
25%       0.000000e+00     0.000000e+00  ...  5.000000e+01  0.000000e+00   
50%       0.000000e+00     0.000000e+00  ...  5.400000e+01  0.000000e+00   
75%       0.000000e+00     0.000000e+00  ...  5.405208e+01  3.777740e-01   
max       1.000000e+00     1.000000e+00  ...  8.040961e+03  1.099626e+04   

           Tot size           IAT        Number      Magnitue        Radius  \
count  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06   
mean   1.248978e+02  8.317382e+07  9.497998e+00  1.312711e+01  4.728151e+01   
std    2.429223e+02  1.703857e+07  8.187710e-01  8.639921e+00  2.294819e+02   
min    4.200000e+01  0.000000e+00  1.000000e+00  9.165151e+00  0.000000e+00   
25%    5.000000e+01  8.307157e+07  9.500000e+00  1.000000e+01  0.000000e+00   
50%    5.400000e+01  8.312452e+07  9.500000e+00  1.039230e+01  0.000000e+00   
75%    5.406000e+01  8.334390e+07  9.500000e+00  1.039675e+01  5.059213e-01   
max    1.309800e+04  1.676394e+08  1.500000e+01  1.252094e+02  1.555106e+04   

         Covariance      Variance        Weight  
count  1.048575e+06  1.048575e+06  1.048575e+06  
mean   3.147998e+04  9.635824e-02  1.414999e+02  
std    3.645895e+05  2.327718e-01  2.105725e+01  
min    0.000000e+00  0.000000e+00  1.000000e+00  
25%    0.000000e+00  0.000000e+00  1.415500e+02  
50%    0.000000e+00  0.000000e+00  1.415500e+02  
75%    1.370916e+00  8.000000e-02  1.415500e+02  
max    1.372844e+08  1.000000e+00  2.446000e+02  

[8 rows x 46 columns]

In [6]:
iot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 47 columns):
 #   Column           Non-Null Count    Dtype  
---  ------           --------------    -----  
 0   flow_duration    1048575 non-null  float64
 1   Header_Length    1048575 non-null  float64
 2   Protocol Type    1048575 non-null  float64
 3   Duration         1048575 non-null  float64
 4   Rate             1048575 non-null  float64
 5   Srate            1048575 non-null  float64
 6   Drate            1048575 non-null  float64
 7   fin_flag_number  1048575 non-null  int64  
 8   syn_flag_number  1048575 non-null  int64  
 9   rst_flag_number  1048575 non-null  int64  
 10  psh_flag_number  1048575 non-null  int64  
 11  ack_flag_number  1048575 non-null  int64  
 12  ece_flag_number  1048575 non-null  int64  
 13  cwr_flag_number  1048575 non-null  int64  
 14  ack_count        1048575 non-null  float64
 15  syn_count        1048575 non-null  float64
 16  fin_count        1

In [7]:
print(iot.shape)

(1048575, 47)


In [8]:
iot.isnull().sum()

flow_duration      0
Header_Length      0
Protocol Type      0
Duration           0
Rate               0
Srate              0
Drate              0
fin_flag_number    0
syn_flag_number    0
rst_flag_number    0
psh_flag_number    0
ack_flag_number    0
ece_flag_number    0
cwr_flag_number    0
ack_count          0
syn_count          0
fin_count          0
urg_count          0
rst_count          0
HTTP               0
HTTPS              0
DNS                0
Telnet             0
SMTP               0
SSH                0
IRC                0
TCP                0
UDP                0
DHCP               0
ARP                0
ICMP               0
IPv                0
LLC                0
Tot sum            0
Min                0
Max                0
AVG                0
Std                0
Tot size           0
IAT                0
Number             0
Magnitue           0
Radius             0
Covariance         0
Variance           0
Weight             0
label              0
dtype: int64

In [9]:
iot.duplicated().sum()

65556

In [10]:
#iot.dropna(inplace=True)


# Provide the correct absolute file path to your CSV file
file_path = r"C:\Users\hp\Documents\working_projects\AI_ML\cleaned_iot.csv"

# Read the CSV file and create the DataFrame
iot = pd.read_csv(file_path)

# Drop rows with missing values
iot.dropna(inplace=True)


In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [12]:
X =iot.drop("label",axis=1)
Y=iot['label']

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [14]:
rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)

In [22]:
rf_classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [16]:
iot.to_csv('cleaned_iot.csv',index=False)

In [17]:
df=pd.read_csv("cleaned_iot.csv")

In [18]:
total_rows=df.shape[0]
half_rows=total_rows//2

first_half=df.iloc[:half_rows]
second_half=df.iloc[half_rows:]


In [19]:
first_half.to_csv('first_half.csv',index=False)
second_half.to_csv('second_half.csv',index=False)

In [26]:
#from google.colab import files
#files.download('first_half.csv')
#files.download('second_half.csv')
import pandas as pd
first_half=pd.read_csv("first_half.csv")
second_half=pd.read_csv("second_half.csv")


In [24]:
X =first_half.drop("label",axis=1)
Y=first_half['label']

In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [28]:
rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)

In [29]:
rf_classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [30]:
Y_pres=rf_classifier.predict(X_test)

In [31]:
accuracy=accuracy_score(Y_test,Y_pres)
conf_matrix=confusion_matrix(Y_test,Y_pres)
class_report=classification_report(Y_test,Y_pres)

C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
print(f'Accuracy: {accuracy:.2f}')
#print('Confusion Matrix:\n', conf_matrix)
print('Classification Report:\n', class_report)

Accuracy: 0.99
Confusion Matrix:
 [[   0    0    0 ...    0    0    0]
 [   0 2433    0 ...    0    0    0]
 [   0    5    0 ...    0    0    0]
 ...
 [   0    1    0 ...    0    0    0]
 [   0    1    0 ...    0   77    0]
 [   0    3    0 ...    0    0    0]]
Classification Report:
                          precision    recall  f1-score   support

       Backdoor_Malware       0.00      0.00      0.00         6
          BenignTraffic       0.86      0.99      0.92      2470
       BrowserHijacking       0.00      0.00      0.00        14
       CommandInjection       0.67      0.15      0.25        13
 DDoS-ACK_Fragmentation       1.00      0.99      0.99       679
        DDoS-HTTP_Flood       0.95      0.95      0.95        66
        DDoS-ICMP_Flood       1.00      1.00      1.00     16209
DDoS-ICMP_Fragmentation       0.99      0.99      0.99      1014
      DDoS-PSHACK_Flood       1.00      1.00      1.00      9163
       DDoS-RSTFINFlood       1.00      1.00      1.00      905

In [33]:
X =second_half.drop("label",axis=1)
Y=second_half['label']

In [34]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [35]:
rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)

In [36]:
rf_classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [37]:
accuracy=accuracy_score(Y_test,Y_pres)
conf_matrix=confusion_matrix(Y_test,Y_pres)
class_report=classification_report(Y_test,Y_pres)

C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3_1\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
print(f'Accuracy: {accuracy:.2f}')
#print('Confusion Matrix:\n', conf_matrix)
print('Classification Report:\n', class_report)

Accuracy: 0.09
Confusion Matrix:
 [[ 0  0  0 ...  0  0  0]
 [ 0 50  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
Classification Report:
                          precision    recall  f1-score   support

       Backdoor_Malware       0.00      0.00      0.00         6
          BenignTraffic       0.02      0.02      0.02      2391
       BrowserHijacking       0.00      0.00      0.00        13
       CommandInjection       0.00      0.00      0.00        11
 DDoS-ACK_Fragmentation       0.00      0.00      0.00       610
        DDoS-HTTP_Flood       0.00      0.00      0.00        52
        DDoS-ICMP_Flood       0.15      0.15      0.15     16091
DDoS-ICMP_Fragmentation       0.01      0.01      0.01       967
      DDoS-PSHACK_Flood       0.09      0.09      0.09      9195
       DDoS-RSTFINFlood       0.09      0.09      0.09      9112
         DDoS-SYN_Flood       0.09      0.08      0.08      9285
     

In [1]:
from collections import Counter
import matplotlib.pyplot as plt
